Algoritmo "CASO andares preços"

//Algoritimo de caso que indica um andar ao respectivo preço
Var

   preco:  caractere
   andar: inteiro


Inicio

      escreva ("Digite o andar que deseja comprar: ")
      leia(andar)
      escreval
      
      escolha andar

              caso 1

              escreval ("Preço nesse andar é, R$ 200.000,00")
              
              caso 2,3,4

              escreval ("Preço nesse andar é, R$ 220.000,00")
              
              caso 5,6,7

              escreval ("Preço nesse andar é, R$ 250.000,00")
              
              caso 8,9,10

              escreval ("Preço nesse andar é, R$ 300.000,00")
              
              caso 11,12,13,14,15,16,17,18

              escreval ("Preço nesse andar é, R$ 500.000,00")
              

              
              outrocaso
              
              escreval ("Andar inexistente, não tem preço, digite apenas do 1° ao 18°")
              

              


       fimescolha
       



Fimalgoritmo