Var

   aluno : caractere
   nota1, nota2, nota3, nota4, media: real
   






Inicio

      escreva("O nome do Aluno(a): ")
      leia(aluno)
      
      escreva("Digite a 1ªnota: ")
      leia(nota1)
      
      escreva("Digite a 2ªnota: ")
      leia(nota2)
      
      escreva("Digite a 3ªnota: ")
      leia(nota3)
      
      escreva("Digite a 4ªnota: ")
      leia(nota4)
      
      media <- (nota1 + nota2 + nota3 + nota4)/4
      
      escreval("Aluno ", aluno)
      escreval("Nota avaliação 1: ", nota1)
      escreval("Nota avaliação 2: ", nota3)
      escreval("Nota avaliação 3: ", nota3)
      escreval("Nota avaliação 4: ", nota4)
      
      escreval("A média final é de:", media)
      


Fimalgoritmo