Algoritmo "Enquanto soma e média"

Var

    nota, somanotas: real
    aluno: caractere
    contador: inteiro

Inicio

     nota <- 0
     
     escreval ("Digite o nome do aluno: ")
     Leia (aluno)
     
     contador <- 1
     enquanto contador < 5 faca
     escreval ("Digite a nota", contador,": ")
     leia(nota)
     
     somanotas <- somanotas + nota
     contador <- contador + 1
     
     fimenquanto
     
     escreval ("Aluno: ",aluno)
     escreval ("Média:", somanotas/4)
      

Fimalgoritmo