Algoritmo "Enquanto faça entre 1 e 10"

Var

   numero: inteiro

Inicio

      Escreval ("digite um número:")
      leia (numero)
      
      enquanto ( numero < 1 ) ou (numero > 10) faca
      
      escreval ("Digite um número entre 1 e 10!")
      escreval ("Digite novamente:")
      leia (numero)
      
      fimenquanto
      
      escreval ("Muito bem, vc digitou o número, ", numero)


Fimalgoritmo