Algoritmo "exercício fatorial"

Var

   numero, contador : inteiro
   
   fatorial: real
   


Inicio

      escreval ("Digite um número")
      leia(numero)
      
      contador <- 1
      fatorial <- numero
      
      enquanto ( contador < numero ) faca
      
       fatorial <- fatorial * contador
       
       contador <- contador + 1
      
      fimenquanto
      
      escreval ("O fatorial de,", contador, " é",fatorial,".")


Fimalgoritmo