Algoritmo "PAR ou IMPAR"

Var

numero: inteiro

Inicio
       //o mod vai usar o resto de uma divisão para dedefinir o resultado
       //no caso tudo divido por 2 = 0 é par, se não impar.
      escreval("Digite um numero inteiro: ")
      leia(numero)
      
      se (numero mod 2 = 0 ) entao
      
      escreval ("O número, ", numero," é PAR.")
      
      senao
      escreval ("O número, ", numero," é IMPAR.")
      
      fimse


Fimalgoritmo