Algoritmo "TABOADA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/05/2026
Var

 numero, contador, resultado: inteiro

Inicio

     contador <- 1
     Escreval ("Digite o numero da Tabuada que deseja")
     leia (numero)
     
     enquanto ( contador <= 10 )  faca
           resultado <- ( numero * contador )
           
           Escreval ( numero, " X ", contador," = ", resultado)
           
           contador <- contador + 1
     
     
     fimenquanto

Fimalgoritmo