Algoritmo "vetor multplica por 2"

Var
      v1: vetor [1..5] de inteiro
      v2: vetor [1..5] de inteiro
      i: inteiro

Inicio

       para i de 1 ate 5 faca

      escreval ("Digite um número: ")
      leia (v1[i])
      v2[i] <- v1[i]*02
      escreval

      fimpara
      escreval("---RESULTADO---")
      escreval
      
      para i de 1 ate 5 faca
       escreval( v1[i], "-", v2[i])


     fimpara

     

       





Fimalgoritmo