Algoritmo "Vetor imprima, contrario"

Var
     letra: vetor [1..5] de caractere
     i : inteiro
Inicio

       para i de 1 ate 5 faca
       
       escreval ( "Digite uma letra: ")
       leia (letra[i])
       
       fimpara
       limpatela
       para i de 1 ate 5 faca
       
       escreval ( "Letra digitada: ", letra[i])
       escreval
       escreval
       fimpara

       escreval ("!!--Ordem inversa--!!")
       escreval
       escreval
       
       para i de 5 ate 1 passo -1 faca

       escreval ( "Letra digitada: ", letra[i])
       escreval

       fimpara
       
       
       
       
       
       
       
Fimalgoritmo